services:
  - type: web
    name: crunevo
    env: python
    buildCommand: pip install -r CRUNEVO/requirements.txt
    startCommand: gunicorn -b 0.0.0.0:$PORT CRUNEVO.run:app
    envVars:
      - key: DATABASE_DIR
        value: /data
