"""add stock and featured to product

Revision ID: d0da1c95a374
Revises: 810dc2c6c5d4
Create Date: 2025-06-09 08:52:13.778990

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d0da1c95a374"
down_revision = "810dc2c6c5d4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.add_column(sa.Column("stock", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("featured", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_column("featured")
        batch_op.drop_column("stock")

    # ### end Alembic commands ###
